[package]
name = "polski-ls"
version = "0.1.0"
edition = "2021"

[dependencies]
tower-lsp-server = "0.22.1"
tokio = { version = "1.48", features = ["io-std", "macros", "rt-multi-thread", "sync"] }
clap = { version = "4.5", features = ["derive"] }
dirs = "6"
